import {
  ShoppingCart, Fuel, UtensilsCrossed, Bus, GraduationCap, Home,
  Droplets, HeartPulse, Gamepad2, Tv, Shirt, Plane, Coffee, MoreHorizontal,
  Car, MapPin, Tablet, Smartphone, ShieldCheck, Star, Shield, Wrench
} from "lucide-react";

export const EXPENSE_CATEGORIES = [
  { id: "mercado", label: "Mercado", icon: ShoppingCart },
  { id: "gasolinera", label: "Gasolinera", icon: Fuel },
  { id: "restaurantes", label: "Restaurantes", icon: UtensilsCrossed },
  { id: "transporte", label: "Transporte", icon: Bus },
  { id: "colegiatura", label: "Colegiatura", icon: GraduationCap },
  { id: "empleada", label: "Empleada", icon: Home },
  { id: "servicios", label: "Agua/Luz/Internet", icon: Droplets },
  { id: "salud", label: "Salud/Farmacia", icon: HeartPulse },
  { id: "entretenimiento", label: "Entretenimiento", icon: Gamepad2 },
  { id: "suscripciones", label: "Suscripciones", icon: Tv },
  { id: "ropa", label: "Ropa", icon: Shirt },
  { id: "viajes", label: "Viajes", icon: Plane },
  { id: "hormiga", label: "Gastos hormiga", icon: Coffee },
  { id: "seguros", label: "Seguros", icon: Shield },
  { id: "mantenimiento", label: "Mantenimiento", icon: Wrench },
  { id: "otros", label: "Otros", icon: MoreHorizontal },
] as const;

export const GOAL_TYPES = [
  { id: "carro", label: "Carro", icon: Car },
  { id: "casa", label: "Casa", icon: Home },
  { id: "viaje", label: "Viaje", icon: MapPin },
  { id: "tablet", label: "iPad/Laptop", icon: Tablet },
  { id: "telefono", label: "Teléfono", icon: Smartphone },
  { id: "emergencia", label: "Fondo de emergencia", icon: ShieldCheck },
  { id: "otro", label: "Otro", icon: Star },
] as const;

export const DEBT_TYPES = [
  "Tarjeta de crédito",
  "Préstamo personal",
  "Visa cuotas",
  "Préstamo vehicular",
  "Hipoteca",
] as const;

export const INSIGHTS = [
  // Conciencia financiera
  "El orden es el primer paso hacia la libertad financiera.",
  "Cada quetzal que registras es un quetzal que controlas.",
  "Saber a dónde va tu dinero es el superpoder que nadie te enseña.",
  "No se trata de cuánto ganas, sino de cuánto queda después de tus decisiones.",
  "Tu yo de dentro de 5 años te va a agradecer lo que haces hoy.",
  "Un gasto hormiga de Q20 al día son Q600 al mes. Casi Q7,200 al año.",
  "La meta no es ser rico. La meta es que el dinero no te quite el sueño.",
  "Pequeños ajustes hoy = grandes diferencias mañana.",
  "En Guatemala, la mayoría no tiene problemas de ingresos, tiene problemas de orden.",
  "Flowi no te juzga. Te acompaña.",
  // Hábitos
  "El presupuesto no es una jaula. Es un mapa.",
  "Cada deuda que pagás es una cadena que te quitás.",
  "Ahorrar no es lo que sobra. Ahorrar es lo primero que apartás.",
  "No comparés tu inicio con el medio de alguien más.",
  "El dinero sigue a la atención. Lo que revisás, mejora.",
  "Una emergencia sin fondo es una deuda disfrazada.",
  "La quincena no es para gastar todo. Es para avanzar.",
  "Si no sabés cuánto gastás en mercado, tu mercado te controla a vos.",
  "El ahorro más poderoso es el que ni sentís — el automático.",
  "Revisar tus gastos 5 minutos al día vale más que cualquier curso de finanzas.",
  // Mentalidad
  "La libertad financiera empieza cuando el miedo a fin de mes desaparece.",
  "No es cuánto ganás. Es cuánto guardás de lo que ganás.",
  "Tu tarjeta de crédito no es ingreso extra. Es deuda adelantada.",
  "Cada vez que decís no a un gasto innecesario, le decís sí a tu futuro.",
  "El fondo de emergencia no es pesimismo. Es inteligencia.",
  "En 10 años no vas a recordar en qué gastaste, pero sí vas a vivir con lo que ahorraste.",
  "Las metas sin número son solo deseos. Las metas con número son planes.",
  "No necesitás ganar más para empezar. Necesitás ordenar lo que tenés.",
  "El estrés financiero es el más silencioso. Flowi está aquí para reducirlo.",
  "Cada registro que hacés es un voto por la versión más ordenada de vos.",
  // Guatemala y contexto local
  "Hoy es un buen día para revisar tus compromisos del mes.",
  "Los bancos guatemaltecos cobran hasta 36% anual en tarjetas. Cada quetzal de deuda cuesta caro.",
  "La quincena del 15 y fin de mes es una ventaja. Dos chances al mes para ordenarte.",
  "El aguinaldo no es ingreso extra. Es ingreso diferido. Planificalo como tal.",
  "Un fondo de emergencia en Guatemala debería cubrir al menos 3 meses de gastos fijos.",
  "La inflación en Guatemala come el ahorro que no está invertido. El dinero quieto se encoge.",
  "Pagar en cuotas sin interés puede ser inteligente. Pagar en cuotas con interés casi nunca lo es.",
  "El bono 14 es una oportunidad de liquidar deuda cara antes de que siga creciendo.",
  "En Guatemala el IGSS cubre poco. Un fondo de salud propio no es lujo, es necesidad.",
  "Vivir al día no es un problema de ingresos. Es un problema de sistema. Flowi es tu sistema.",
  // Psicología del dinero
  "El dinero amplifica quién sos. Si sos ordenado, amplifica orden. Si sos caótico, amplifica caos.",
  "Gastar para impresionar a otros es alquilar felicidad con dinero que no tenés.",
  "El precio de algo se mide en horas de tu vida. ¿Vale la pena ese gasto en horas tuyas?",
  "La envidia financiera te hace gastar en cosas que no necesitás para impresionar a gente que no te importa.",
  "Comprar cosas que no necesitás con dinero que no tenés es la trampa más vieja del mundo.",
  "La satisfacción de ver crecer tu ahorro supera por mucho la del gasto impulsivo.",
  "El dolor de pagar en efectivo es útil. Te hace más consciente del valor real de las cosas.",
  "No existe el dinero de la suerte. Existe la preparación que te permite aprovechar oportunidades.",
  "El rico promedio no tiene carros caros. Tiene activos que generan mientras duerme.",
  "Ser frugal no es ser tacaño. Es elegir conscientemente en qué sí vale la pena gastar.",
  // Deudas
  "Pagar el mínimo de la tarjeta es la ilusión más cara que existe.",
  "La deuda más urgente de pagar no es la más grande. Es la que cobra más interés.",
  "Un préstamo personal para pagar tarjetas puede tener sentido si la tasa es menor.",
  "Cada mes que no pagás más del mínimo, el banco gana. Vos perdés.",
  "Salir de deudas no requiere ingresos extraordinarios. Requiere un plan ordinario ejecutado con consistencia.",
  "La estrategia bola de nieve funciona porque la motivación importa tanto como los números.",
  "Antes de tomar una deuda nueva, preguntate: ¿qué activo o experiencia irremplazable me da esto?",
  "Una deuda bien usada construye. Una deuda mal usada destruye. La diferencia es el para qué.",
  "El interés compuesto trabaja a tu favor en el ahorro. Y en tu contra en las deudas.",
  "Consolidar deudas puede ahorrarte miles si conseguís una tasa menor. Vale la pena investigar.",
  // Ahorro e inversión
  "El mejor momento para empezar a ahorrar fue hace 10 años. El segundo mejor momento es hoy.",
  "Q500 al mes durante 10 años a 6% de rendimiento son más de Q80,000. El tiempo es el ingrediente secreto.",
  "Diversificar no es complicado. Significa no poner todos los huevos en la misma canasta.",
  "Una cuenta de ahorro en dólares protege tu poder adquisitivo cuando el quetzal pierde valor.",
  "Invertir no requiere ser experto. Requiere empezar con poco, aprender y ser consistente.",
  "El fondo de emergencia va en liquidez, no en inversiones. Tiene que estar disponible en 24 horas.",
  "Automatizar el ahorro elimina la fuerza de voluntad de la ecuación. Y eso es bueno.",
  "No esperés el momento perfecto para invertir. El mercado siempre va a parecer incierto.",
  "La diferencia entre ahorro e inversión es el tiempo. Corto plazo es ahorro. Largo plazo es inversión.",
  "Tener 3 meses de gastos en un fondo de emergencia cambia completamente tu nivel de estrés.",
  // Trabajo y productividad financiera
  "Tu ingreso es tu herramienta más poderosa. Invertir en tus habilidades siempre da retorno.",
  "Una habilidad nueva puede valer más que cualquier ahorro. Aprendé algo que el mercado pague bien.",
  "Negociar tu salario una vez puede valer años de ahorro. La mayoría nunca lo intenta.",
  "El tiempo libre comprado con dinero vale más que el dinero mismo. Optimizá para libertad, no para lujo.",
  "Un ingreso extra de Q1,000 al mes aplicado a deudas puede cambiar tu vida en 2 años.",
  "El emprendimiento no es para todos, pero diversificar ingresos sí debería serlo.",
  "Si tu ingreso depende de una sola fuente, sos más vulnerable de lo que creés.",
  "Invertir en tu salud física y mental genera retornos financieros reales. Enfermarse sale caro.",
  "Las personas con mejores finanzas no son las que más ganan. Son las que menos desperdician.",
  "Tu red de contactos es un activo financiero. Cultivala como tal.",
  // Reflexiones profundas
  "El dinero es energía. Fluye hacia donde le prestas atención con intención.",
  "La abundancia no es tener mucho. Es no necesitar más de lo que tenés.",
  "Ordenar tus finanzas es ordenar una parte importante de tu mente.",
  "La paz financiera no es un número en el banco. Es saber que podés manejar lo que venga.",
  "Cada decisión financiera pequeña es un ladrillo. Al final construyen una casa o un hoyo.",
  "El dinero que gastás en experiencias tiende a dar más felicidad que el dinero en cosas.",
  "La gratitud por lo que tenés es el antídoto contra el consumismo inconsciente.",
  "Construir riqueza es lento, aburrido y consistente. Todo lo contrario a como lo venden.",
  "El verdadero lujo no es el carro ni la ropa. Es no tener que revisar tu cuenta antes de pagar.",
  "Empezar es más importante que empezar perfecto. Abrí Flowi, registrá el primer gasto y seguí.",
];

export const formatQ = (amount: number): string => {
  return `Q${amount.toLocaleString("es-GT", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
};

// ─── Grupos de categorías para Análisis ───────────────────────────────────────
export const CATEGORY_GROUPS = [
  {
    id: "casa",
    label: "Casa",
    color: "#10B981",
    categories: ["mercado", "empleada", "servicios", "mantenimiento"],
  },
  {
    id: "transporte",
    label: "Transporte",
    color: "#3B82F6",
    categories: ["gasolinera", "transporte"],
  },
  {
    id: "educacion",
    label: "Educación",
    color: "#8B5CF6",
    categories: ["colegiatura"],
  },
  {
    id: "salud",
    label: "Salud",
    color: "#EF4444",
    categories: ["salud"],
  },
  {
    id: "entretenimiento",
    label: "Entretenimiento",
    color: "#F59E0B",
    categories: ["restaurantes", "entretenimiento", "suscripciones"],
  },
  {
    id: "estilo",
    label: "Estilo de vida",
    color: "#EC4899",
    categories: ["ropa", "viajes", "hormiga"],
  },
  {
    id: "proteccion",
    label: "Protección",
    color: "#64748B",
    categories: ["seguros"],
  },
  {
    id: "otros",
    label: "Otros",
    color: "#6B7280",
    categories: ["otros"],
  },
] as const;

// ─── Técnicas de ahorro ────────────────────────────────────────────────────────
export const SAVING_TIPS = [
  {
    id: "cafe_fantasma",
    emoji: "☕",
    title: "Café fantasma",
    description: "Por cada café o antojo, guardá la misma cantidad. Tu futuro vos te lo agradece.",
    triggerCategories: ["restaurantes", "hormiga"],
    triggerAlways: false,
  },
  {
    id: "impulso_48h",
    emoji: "⏱️",
    title: "Regla del impulso",
    description: "Esperá 48 horas antes de compras no esenciales. Si en 2 días lo seguís queriendo, es tuyo.",
    triggerCategories: ["ropa", "viajes", "entretenimiento"],
    minAmount: 200,
    triggerAlways: false,
  },
  {
    id: "redondeo",
    emoji: "🔄",
    title: "Redondeo invisible",
    description: "Redondeá este gasto al siguiente centenar y mové la diferencia a tu fondo de ahorro.",
    triggerCategories: [],
    triggerAlways: true,
  },
  {
    id: "sobre_quincenal",
    emoji: "💌",
    title: "Sobre quincenal",
    description: "Cada quincena apartá Q100-Q200 en un sobre físico o cuenta separada. No lo toques.",
    triggerCategories: [],
    triggerAlways: true,
  },
  {
    id: "reto_52",
    emoji: "📅",
    title: "Reto de las 52 semanas",
    description: "Semana 1 guardás Q10, semana 2 Q20... Al final del año tenés más de Q13,000.",
    triggerCategories: [],
    triggerAlways: true,
  },
  {
    id: "mercado_lista",
    emoji: "🛒",
    title: "Lista antes de entrar",
    description: "Ir al mercado sin lista puede costarte hasta 30% más. Escribila antes de salir.",
    triggerCategories: ["mercado"],
    triggerAlways: false,
  },
  {
    id: "gasolina_lleno",
    emoji: "⛽",
    title: "Tanque lleno vs medio",
    description: "Llenar el tanque completo en vez de mitades te ahorra hasta Q80 al mes en paradas extra.",
    triggerCategories: ["gasolinera"],
    triggerAlways: false,
  },
  {
    id: "subscripciones_auditoria",
    emoji: "📱",
    title: "Auditoría de suscripciones",
    description: "Contá cuántas suscripciones tenés activas. La mayoría paga 2-3 que no usa.",
    triggerCategories: ["suscripciones"],
    triggerAlways: false,
  },
  {
    id: "restaurante_cocina",
    emoji: "🍱",
    title: "Cocina una vez más",
    description: "Sustituir una salida a restaurante por semana puede ahorrarte Q400-Q600 al mes.",
    triggerCategories: ["restaurantes"],
    triggerAlways: false,
  },
  {
    id: "ropa_30_usos",
    emoji: "👕",
    title: "Regla de los 30 usos",
    description: "Antes de comprar ropa preguntate: me lo voy a poner 30 veces? Si no, dejalo.",
    triggerCategories: ["ropa"],
    triggerAlways: false,
  },
  {
    id: "pago_extra_deuda",
    emoji: "💳",
    title: "Q100 extra a la deuda",
    description: "Agregar Q100 extra al mes a tu deuda con más interés puede acortarla varios meses.",
    triggerCategories: [],
    triggerAlways: true,
  },
  {
    id: "regla_50_30_20",
    emoji: "📊",
    title: "Regla 50/30/20",
    description: "50% necesidades, 30% gustos, 20% ahorro y deudas. Un punto de partida simple y poderoso.",
    triggerCategories: [],
    triggerAlways: true,
  },
  {
    id: "efectivo_un_dia",
    emoji: "💵",
    title: "Pagá en efectivo un día",
    description: "Usar efectivo activa más el cerebro que la tarjeta. Probalo un día y notás la diferencia.",
    triggerCategories: [],
    triggerAlways: true,
  },
  {
    id: "ahorro_primero",
    emoji: "🥇",
    title: "Pagarte primero",
    description: "El día que caiga tu quincena, mové tu ahorro antes de gastar cualquier cosa.",
    triggerCategories: [],
    triggerAlways: true,
  },
  {
    id: "meta_visual",
    emoji: "🎯",
    title: "Foto de tu meta",
    description: "Pon como fondo de pantalla lo que estás ahorrando. Ver tu meta todos los días cambia decisiones.",
    triggerCategories: [],
    triggerAlways: true,
  },
  {
    id: "precio_horas",
    emoji: "⏰",
    title: "Precio en horas de trabajo",
    description: "Antes de comprar algo, calculá cuántas horas de trabajo cuesta. Cambia la perspectiva.",
    triggerCategories: [],
    triggerAlways: true,
  },
  {
    id: "compras_manana",
    emoji: "🌅",
    title: "Comprá de mañana",
    description: "Las decisiones de compra por la noche suelen ser más impulsivas. Esperá al día siguiente.",
    triggerCategories: ["entretenimiento", "ropa", "viajes"],
    triggerAlways: false,
  },
  {
    id: "salud_preventiva",
    emoji: "🏥",
    title: "Inversión preventiva",
    description: "Un chequeo médico anual cuesta mucho menos que una emergencia. Agendalo este mes.",
    triggerCategories: ["salud"],
    triggerAlways: false,
  },
  {
    id: "transporte_combinar",
    emoji: "🚗",
    title: "Combiná viajes",
    description: "Agrupar mandados en un solo recorrido puede ahorrarte Q200-Q400 al mes en gasolina.",
    triggerCategories: ["gasolinera", "transporte"],
    triggerAlways: false,
  },
  {
    id: "entretenimiento_gratis",
    emoji: "🎪",
    title: "Entretenimiento sin costo",
    description: "Guatemala tiene parques, museos, eventos y naturaleza gratuita. Exploralo este fin de semana.",
    triggerCategories: ["entretenimiento"],
    triggerAlways: false,
  },
  {
    id: "seguro_cotizar",
    emoji: "🛡️",
    title: "Cotizá tu seguro",
    description: "Los seguros se pueden renegociar. Si llevas más de 2 años sin cotizar, probablemente pagás de más.",
    triggerCategories: ["seguros"],
    triggerAlways: false,
  },
  {
    id: "internet_plan",
    emoji: "📶",
    title: "Revisá tu plan de datos",
    description: "Muchos pagan por plan de datos que no usan completamente. Revisá si podés bajar un nivel.",
    triggerCategories: ["servicios", "suscripciones"],
    triggerAlways: false,
  },
  {
    id: "regalo_significativo",
    emoji: "🎁",
    title: "Regalos con significado",
    description: "Un regalo hecho a mano o una experiencia compartida suele valer más que uno caro comprado.",
    triggerCategories: ["otros"],
    triggerAlways: false,
  },
  {
    id: "viaje_temporada_baja",
    emoji: "✈️",
    title: "Viajá en temporada baja",
    description: "Los mismos destinos pueden costar hasta 40% menos fuera de feriados y vacaciones.",
    triggerCategories: ["viajes"],
    triggerAlways: false,
  },
  {
    id: "agua_casa",
    emoji: "💧",
    title: "Agua en casa",
    description: "Llevar agua de casa en vez de comprarla puede ahorrarte Q300-Q500 al mes fácilmente.",
    triggerCategories: ["hormiga", "restaurantes"],
    triggerAlways: false,
  },
  {
    id: "mantenimiento_preventivo",
    emoji: "🔧",
    title: "Mantenimiento a tiempo",
    description: "Mantener el carro al día cuesta la mitad que reparar una falla por descuido.",
    triggerCategories: ["mantenimiento", "transporte"],
    triggerAlways: false,
  },
  {
    id: "compra_mayoreo",
    emoji: "📦",
    title: "Comprá al mayoreo",
    description: "Artículos que usás siempre salen más baratos en Costco, PriceSmart o por mayor. Calculá el ahorro.",
    triggerCategories: ["mercado"],
    triggerAlways: false,
  },
  {
    id: "no_comprar_hambre",
    emoji: "🍔",
    title: "Nunca comprés con hambre",
    description: "Ir al mercado con hambre puede aumentar tu gasto hasta un 25%. Comé antes de salir.",
    triggerCategories: ["mercado", "restaurantes"],
    triggerAlways: false,
  },
  {
    id: "cuenta_dolares",
    emoji: "💱",
    title: "Guardá en dólares",
    description: "Tener parte de tu ahorro en dólares protege contra la inflación y te da más opciones.",
    triggerCategories: [],
    triggerAlways: true,
  },
  {
    id: "revision_mensual",
    emoji: "📋",
    title: "Cita mensual con tus finanzas",
    description: "Agendá 20 minutos al mes para revisar gastos, ajustar metas y celebrar tus avances.",
    triggerCategories: [],
    triggerAlways: true,
  },
] as const;

export type SavingTip = (typeof SAVING_TIPS)[number];
